### ISSUE TITLE
Fix "Go to Tarallo" button

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#46]
It should use the default browser, not "firefox", to prevent this error from happening:
```
Traceback (most recent call last):
  File "./main_with_gui.py", line 311, in <lambda>
    self.website_button.clicked.connect(lambda: sp.Popen(["firefox", website_link]))
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'firefox': 'firefox'
Aborted
```

**Comment by lvps** [comment]
"xdg-open" or a similar command should have the desired effect

Il sab 21 dic 2019, 19:16 e-caste <notifications@github.com> ha scritto:
